version: '3.9'

services:

  redis:
    image: redis:6.2.3-alpine
    ports:
      - "6379:6379"

  php:
    container_name: php
    hostname: php
    build:
      context: ./back
      dockerfile: Dockerfile-beta
    ports:
      - "8001:8001"
    volumes:
      - ./back:/app/src
      - vendor:/app/src/vendor
    restart: always
    links:
      - redis
    env_file:
      - ./back/.env
    stdin_open: true # run -i
    tty: true # run -t

  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./front
      dockerfile: Dockerfile-beta
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nginx/default-prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

volumes:
  vendor: